import streamlit as st
import torch
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from fpdf import FPDF
import tempfile
import os

# Try importing our new 2.5D backend
try:
    from inference_engine import TumorSystem
    BACKEND_LOADED = True
except ImportError:
    BACKEND_LOADED = False

# --- 1. PAGE CONFIGURATION ---
st.set_page_config(
    page_title="BoneSegNet | Clinical UI",
    page_icon="🦴",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- 2. CUSTOM CSS ---
st.markdown("""
<style>
    .block-container { padding-top: 1rem; padding-bottom: 5rem; }
    h1 { color: #2c3e50; font-family: 'Segoe UI', sans-serif; font-weight: 600; }
    [data-testid="stMetricValue"] { font-size: 2rem !important; color: #27ae60; }
    .stButton>button { width: 100%; border-radius: 6px; font-weight: bold; background-color: #2c3e50; color: white;}
</style>
""", unsafe_allow_html=True)

# --- 3. SYSTEM INITIALIZATION ---
@st.cache_resource
def load_system():
    if BACKEND_LOADED:
        return TumorSystem()
    return None

system = load_system()

# Define a custom vivid Green colormap for strict boundaries
green_cmap = ListedColormap(['none', '#00FF00'])

# --------------------------------------------------
# 4. CLINICAL PDF GENERATOR (SEGMENTATION FOCUSED)
# --------------------------------------------------
def create_pdf(p_data, res, scan_tensor, slices):
    scan_tensor = scan_tensor.cpu().detach()
    d_max, h_max, w_max = scan_tensor.shape[2], scan_tensor.shape[3], scan_tensor.shape[4]
    
    safe_slices = [
        min(slices[0], d_max - 1), # Axial Slice Index
        min(slices[1], h_max - 1), # Coronal Slice Index
        min(slices[2], w_max - 1)  # Sagittal Slice Index
    ]
    
    class ClinicalReport(FPDF):
        def header(self):
            self.rect(5, 5, 200, 287)
            self.set_font('Arial', 'B', 16)
            self.cell(0, 10, 'BoneSegNet Radiology Report', 0, 1, 'C')
            self.set_font('Arial', 'I', 10)
            self.cell(0, 5, '2.5D AI-Assisted Osteology Segmentation System', 0, 1, 'C')
            self.line(10, 25, 200, 25)
            self.ln(15)
        def footer(self):
            self.set_y(-20)
            self.set_font('Arial', 'I', 8)
            self.set_text_color(128)
            self.cell(0, 10, f'Page {self.page_no()} | Generated by BoneSegNet Triage', 0, 0, 'C')

    def save_view(tensor, mask_vol, slice_idx, axis_id, title):
        # CLINICAL STANDARD ROTATIONS: .T (transpose) + flipud (flip upright)
        if axis_id == 0:   # Axial (Top-Down)
            img = tensor[0, 0, slice_idx, :, :].numpy()
            mask = mask_vol[slice_idx, :, :] if mask_vol is not None else None
        elif axis_id == 1: # Coronal (Front)
            img = np.flipud(tensor[0, 0, :, slice_idx, :].numpy().T)
            mask = np.flipud(mask_vol[:, slice_idx, :].T) if mask_vol is not None else None
        else:              # Sagittal (Side)
            img = np.flipud(tensor[0, 0, :, :, slice_idx].numpy().T)
            mask = np.flipud(mask_vol[:, :, slice_idx].T) if mask_vol is not None else None

        fig, ax = plt.subplots(1, 2, figsize=(8, 4))
        plt.subplots_adjust(wspace=0.1)

        ax[0].imshow(img, cmap="gray", aspect='auto')
        ax[0].set_title(f"{title} - Raw Window", fontsize=10)
        ax[0].axis('off')

        ax[1].imshow(img, cmap="gray", aspect='auto')
        if mask is not None and mask.max() > 0:
            # Alpha 1.0 + vmin/vmax for perfect solid green visibility
            masked_data = np.ma.masked_where(mask < 0.5, mask)
            ax[1].imshow(masked_data, cmap=green_cmap, alpha=1.0, aspect='auto', vmin=0, vmax=1)
        
        ax[1].set_title(f"{title} - AI Mask", fontsize=10)
        ax[1].axis('off')

        fd, path = tempfile.mkstemp(suffix=".png")
        os.close(fd)
        plt.savefig(path, bbox_inches='tight', dpi=150)
        plt.close(fig)
        return path

    pdf = ClinicalReport()
    pdf.set_auto_page_break(auto=True, margin=20)

    # PAGE 1
    pdf.add_page()
    pdf.set_font("Arial", 'B', 12)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 8, "  1. Patient Demographics", 0, 1, 'L', fill=True)
    pdf.ln(4)
    
    pdf.set_font("Arial", size=10)
    pdf.cell(50, 6, f"Patient ID: {p_data['id']}", 0, 0)
    pdf.cell(0, 6, f"Scan Date: {p_data['date']}", 0, 1)
    pdf.ln(5)

    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 8, "  2. Segmentation Assessment", 0, 1, 'L', fill=True)
    pdf.ln(4)
    
    is_pos = res['affected_slices'] > 0
    color = (200, 50, 50) if is_pos else (50, 150, 50)

    pdf.set_font("Arial", 'B', 11)
    pdf.cell(45, 6, "AI Output:", 0, 0)
    pdf.set_text_color(*color)
    pdf.cell(0, 6, res['diagnosis'].upper(), 0, 1)
    pdf.set_text_color(0)
    
    pdf.set_font("Arial", size=10)
    pdf.cell(45, 6, "Total Affected Slices:", 0, 0)
    pdf.cell(0, 6, str(res['affected_slices']), 0, 1)
    pdf.cell(45, 6, "Lesion Volume (px):", 0, 0)
    pdf.cell(0, 6, str(res['lesion_volume_px']), 0, 1)
    pdf.ln(5)

    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 8, "  3. Primary View (Axial Overlay)", 0, 1, 'L', fill=True)
    pdf.ln(2)

    axial_path = save_view(scan_tensor, res['heatmap'], safe_slices[0], 0, "Axial View")
    pdf.image(axial_path, x=20, w=170)
    try: os.remove(axial_path)
    except: pass

    # PAGE 2 (Views)
    pdf.add_page()
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 8, "  4. Multi-Planar Segmentation", 0, 1, 'L', fill=True)
    pdf.ln(6)

    cor_path = save_view(scan_tensor, res['heatmap'], safe_slices[1], 1, "Coronal View")
    pdf.image(cor_path, x=25, w=160)
    try: os.remove(cor_path)
    except: pass
    pdf.ln(6)

    sag_path = save_view(scan_tensor, res['heatmap'], safe_slices[2], 2, "Sagittal View")
    pdf.image(sag_path, x=25, w=160)
    try: os.remove(sag_path)
    except: pass

    return pdf.output(dest='S').encode('latin-1')

# --- 5. SIDEBAR ---
with st.sidebar:
    st.title("🏥 BoneSegNet")
    st.info("2.5D ResNet34 U-Net++ Triage")
    
    st.header("Patient Data")
    patient_id = st.text_input("Patient ID", "MM-TCIA-405")
    scan_date = st.date_input("Scan Date")
    
    st.divider()
    st.write("Engine Status: 🟢 Online")
    st.write("Model: 2.5D U-Net++ (40keV)")

# --- 6. MAIN PAGE ---
st.title("🦴 2.5D Volumetric Bone Segmentation")

uploaded_file = st.file_uploader("Upload Bone Windowed CT (.pt)", type=["pt"], label_visibility="collapsed")

if uploaded_file is not None:
    scan_tensor = torch.load(uploaded_file, map_location='cpu', weights_only=False)
    if scan_tensor.dim() == 3: scan_tensor = scan_tensor.unsqueeze(0).unsqueeze(0)
    elif scan_tensor.dim() == 4: scan_tensor = scan_tensor.unsqueeze(0)
    
    st.session_state.scan_tensor = scan_tensor

    st.subheader("1. Pre-Inference Scan Verification")
    with st.expander("Show Quality Check", expanded=True):
        d_mid, h_mid, w_mid = scan_tensor.shape[2]//2, scan_tensor.shape[3]//2, scan_tensor.shape[4]//2
        c1, c2, c3 = st.columns(3)
        
        # CLINICAL STANDARD ROTATIONS: .T (transpose) + flipud (flip upright)
        img_ax = scan_tensor[0, 0, d_mid, :, :].numpy()
        img_cor = np.flipud(scan_tensor[0, 0, :, h_mid, :].numpy().T)
        img_sag = np.flipud(scan_tensor[0, 0, :, :, w_mid].numpy().T)
        
        c1.image(img_ax, caption="Axial Window", clamp=True, use_container_width=True)
        c2.image(img_cor, caption="Coronal Window", clamp=True, use_container_width=True)
        c3.image(img_sag, caption="Sagittal Window", clamp=True, use_container_width=True)
        
    st.divider()
    col_run, _ = st.columns([1, 2])
    with col_run:
        if st.button("RUN 2.5D SEGMENTATION", type="primary"):
            with st.spinner("Extracting spatial features across Z-axis..."):
                if BACKEND_LOADED:
                    my_bar = st.progress(0, text="Initializing tensors...")
                    st.session_state.results = system.analyze_scan(scan_tensor, progress_bar=my_bar)
                    my_bar.empty()
                else:
                    st.error("Backend offline")

    if 'results' in st.session_state and st.session_state.results:
        res = st.session_state.results
        st.divider()
        st.subheader("2. Segmentation Metrics")
        
        # 4 Columns to fit the new Confidence Score
        k1, k2, k3, k4 = st.columns(4)
        is_pos = res['affected_slices'] > 0
        
        k1.metric("Clinical Assessment", res['diagnosis'], delta="Lesion Detected" if is_pos else "Clear", delta_color="inverse" if is_pos else "normal")
        k2.metric("Slices Affected", res['affected_slices'])
        k3.metric("Tumor Volume (px)", res['lesion_volume_px'])
        
        conf_text = f"{res['confidence']:.1f}%" if is_pos else "N/A"
        k4.metric("AI Confidence", conf_text)

        st.divider()
        st.subheader("3. Pixel-Level Boundary Localization")
        
        d_size, h_size, w_size = scan_tensor.shape[2], scan_tensor.shape[3], scan_tensor.shape[4]
        c_left, c_mid, c_right = st.columns(3)

        # --- AUTO-TARGETING LOGIC ---
        heatmap = res['heatmap']
        
        # Default to the middle of the scan if no tumor is found
        best_ax, best_cor, best_sag = d_size // 2, h_size // 2, w_size // 2
        
        # If the AI found a tumor, find the slice with the highest pixel density
        if heatmap is not None and heatmap.max() > 0:
            best_ax = int(np.argmax(np.sum(heatmap, axis=(1, 2))))  # Axis 0
            best_cor = int(np.argmax(np.sum(heatmap, axis=(0, 2)))) # Axis 1
            best_sag = int(np.argmax(np.sum(heatmap, axis=(0, 1)))) # Axis 2

        # Sliders now instantly snap to the worst part of the tumor
        ax_sl = c_left.slider("Axial (Axis 0)", 0, d_size-1, best_ax)
        cor_sl = c_mid.slider("Coronal (Axis 1)", 0, h_size-1, best_cor)
        sag_sl = c_right.slider("Sagittal (Axis 2)", 0, w_size-1, best_sag)

        # CLINICAL STANDARD ROTATIONS FOR SLIDERS
        img_ax = scan_tensor[0, 0, ax_sl, :, :].numpy()
        mask_ax = heatmap[ax_sl, :, :] if heatmap is not None else None
        
        img_cor = np.flipud(scan_tensor[0, 0, :, cor_sl, :].numpy().T)
        mask_cor = np.flipud(heatmap[:, cor_sl, :].T) if heatmap is not None else None
        
        img_sag = np.flipud(scan_tensor[0, 0, :, :, sag_sl].numpy().T)
        mask_sag = np.flipud(heatmap[:, :, sag_sl].T) if heatmap is not None else None

        fig, ax = plt.subplots(1, 3, figsize=(15, 5))
        plt.subplots_adjust(wspace=0.1, left=0, right=1, top=1, bottom=0)
        
        def plot_sub(axis, img, mask, title):
            axis.imshow(img, cmap="gray", aspect='auto')
            if mask is not None and mask.max() > 0:
                masked_overlay = np.ma.masked_where(mask < 0.5, mask)
                # vmin=0, vmax=1 forces the transparent-to-green colormap to render properly
                axis.imshow(masked_overlay, cmap=green_cmap, alpha=1.0, aspect='auto', vmin=0, vmax=1)
            axis.set_title(title, fontsize=12, fontweight='bold', pad=10)
            axis.axis('off')
            
        plot_sub(ax[0], img_ax, mask_ax, f"Axial (Slice {ax_sl})")
        plot_sub(ax[1], img_cor, mask_cor, f"Coronal (Slice {cor_sl})")
        plot_sub(ax[2], img_sag, mask_sag, f"Sagittal (Slice {sag_sl})")
        
        st.pyplot(fig, use_container_width=True)

        st.divider()
        st.subheader("📄 Automated Triage Documentation")
        c1, c2 = st.columns([3, 2], gap="large")

        with c1:
            st.markdown("### 🩺 Clinical Action")
            if is_pos:
                st.error("### ⚠ Lytic Lesion Geometry Detected")
                st.markdown("**System Flags:** Strict boundary detection confirmed within Hounsfield bone window. High probability of multiple myeloma or osteosarcoma. Recommend immediate verification of green mask overlays by attending radiologist.")
            else:
                st.success("### ✅ No Boundary Disruption Detected")
                st.markdown("**System Flags:** Trabecular and cortical bone structures appear continuous. No lytic cavities flagged by U-Net++ decoder.")

        with c2:
            st.markdown("### 📑 Export PDF Report")
            with st.container(border=True):
                # Pass the slices in the exact order [Axial, Coronal, Sagittal]
                pdf_bytes = create_pdf({"id": patient_id, "date": scan_date}, res, scan_tensor, [ax_sl, cor_sl, sag_sl])
                st.download_button(
                    label="Download Visual Autopsy (PDF)",
                    data=pdf_bytes,
                    file_name=f"BoneSegNet_{patient_id}.pdf",
                    mime="application/pdf",
                    type="primary",
                    use_container_width=True
                )